set_property PACKAGE_PIN R2 [get_ports {input_1[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {input_1[5]}]
set_property PACKAGE_PIN T1 [get_ports {input_1[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {input_1[4]}]    
set_property PACKAGE_PIN U1 [get_ports {input_1[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {input_1[3]}]
set_property PACKAGE_PIN W2 [get_ports {input_1[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {input_1[2]}] 
set_property PACKAGE_PIN R3 [get_ports {input_1[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {input_1[1]}]
set_property PACKAGE_PIN T2 [get_ports {input_1[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {input_1[0]}]    
   

set_property PACKAGE_PIN L1 [get_ports { led_1[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports { led_1[5]}]
set_property PACKAGE_PIN P1 [get_ports { led_1[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports { led_1[4]}]    
set_property PACKAGE_PIN N3 [get_ports { led_1[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports { led_1[3]}]
set_property PACKAGE_PIN P3 [get_ports { led_1[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports { led_1[2]}] 
set_property PACKAGE_PIN U3 [get_ports { led_1[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports { led_1[1]}]
set_property PACKAGE_PIN W3 [get_ports { led_1[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports { led_1[0]}]  
    
set_property PACKAGE_PIN V15 [get_ports {input_2[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {input_2[5]}]
set_property PACKAGE_PIN W15 [get_ports {input_2[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {input_2[4]}]    
set_property PACKAGE_PIN W17 [get_ports {input_2[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {input_2[3]}]
set_property PACKAGE_PIN W16 [get_ports {input_2[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {input_2[2]}] 
set_property PACKAGE_PIN V16 [get_ports {input_2[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {input_2[1]}]
set_property PACKAGE_PIN V17 [get_ports {input_2[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {input_2[0]}] 
    
set_property PACKAGE_PIN U15 [get_ports {led_2[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_2[5]}]
set_property PACKAGE_PIN W18 [get_ports {led_2[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_2[4]}]    
set_property PACKAGE_PIN V19 [get_ports {led_2[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_2[3]}]
set_property PACKAGE_PIN U19 [get_ports {led_2[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_2[2]}] 
set_property PACKAGE_PIN E19 [get_ports {led_2[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_2[1]}]
set_property PACKAGE_PIN U16 [get_ports {led_2[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_2[0]}]  
   
set_property PACKAGE_PIN V2 [get_ports {s}] 
        set_property IOSTANDARD LVCMOS33 [get_ports {s}]
   
set_property PACKAGE_PIN W5 [get_ports {clock}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {clock}]
    
set_property PACKAGE_PIN W7 [get_ports {cathode[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cathode[6]}]
set_property PACKAGE_PIN W6 [get_ports {cathode[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cathode[5]}]
set_property PACKAGE_PIN U8 [get_ports {cathode[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cathode[4]}]
set_property PACKAGE_PIN V8 [get_ports {cathode[3]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[3]}]
set_property PACKAGE_PIN U5 [get_ports {cathode[2]}]
            set_property IOSTANDARD LVCMOS33 [get_ports {cathode[2]}]
set_property PACKAGE_PIN V5 [get_ports {cathode[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cathode[1]}]
set_property PACKAGE_PIN U7 [get_ports {cathode[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cathode[0]}]
    
set_property PACKAGE_PIN U2 [get_ports {anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]